
export const dataArray = [
  {title: 'Love',
    content: [
      { question: 'When will I meet the true love of my life?' },
      { question: 'Am I going to be in a new relationship soon?' },
      { question: 'Should I move in with my boyfriend?' },
      { question: 'What should I do right now and in the coming months to assure that my relationship will move to the next level?'},
      { question: 'Why did we break up last year?' },
      { question: 'Will it be good for me if I get back with my Ex?' },
      { question: 'How many times will I meet a compatible potential life partner?'},
      { question: 'How will I meet my future husband?'},
      { question: 'Will my husband stay loyal and faithful for the rest of our lives?'},
      { question: 'What does my birth chart show about my relationship this year? What can I do to improve it?'},
      { question: 'What are the things to avoid in my relationship with my boyfriend?'},
      { question: 'Why do I always come back to him?'},
      { question: 'I started a new relationship, but I still think about my Ex, how to finish this connection?'},
      { question: 'Is there anyone loving me secretly? Or is interested in me right now?'},
      { question: 'Am I gonna meet someone new today?' },
      { question: 'Is my current partner the person I will spend all my life with?'},
      { question: 'Is my current boyfriend capable of true love and being a good partner?'},
      { question: 'Does my boyfriend still keep in touch with his Ex?'},
      { question: 'Is my Ex meeting someone now?'},
      { question: 'Why am I single?'},
      { question: 'I am looking for once in a lifetime soulmate. When will I meet him?'},
      { question: 'Do you think that the connection I felt today with someone new will end up into something good?'},
      { question: 'According to my birth details, how compatible am I with my current boyfriend?'},
      { question: 'Am I making right decision breaking up with my boyfriend?'},
      { question: 'I think that my boyfriend is unfaithful, should I really worry about something or it’s all just my imagination?'},
      { question: 'I feel really heartbroken. What should I do?'},
      { question: 'How does my love life look this year?'},
      { question: 'Is it possible for me and my ex to be good friends?'},
      { question: 'The guy I like promised to text me, but still didn’t. Should I connect him first?'},
      { question: 'When will I get married?'},
      { question: 'When will I have kids?'},
      { question: 'Is my boyfriend losing feelings for me? I feel that something has changed between us. What happened?'},
      { question: 'If our relationship ends, who will be the one to make a decision?'},
      { question: 'How long will the relationship with my current boyfriend last?'},
      { question: 'Does my boyfriend want to be a better man for me? Does he want to change?'},
      { question: 'What kind of person should I marry?'},
      { question: 'Do I know my future boyfriend already? Is he the one I already know?'},
      { question: 'Will my boyfriend make a proposal this year? When will we become engaged?'},
      { question: 'What is my purpose in his life? Will we be a couple someday or just stay good friends?'},
      { question: 'He never invites me to his family dinners, what does it mean? He keeps me in a secret or doesn’t love me?'},
      { question: 'Did I make the right decision to stay with my current partner and will I still be able to grow spiritually with him?'},
      { question: 'I got a proposal from my boyfriend. Should I agree? Will our marriage be happy?'},
      { question: 'How to get rid in a right way of a guy who is in love with me but I feel nothing for him?'},
      { question: 'I just broke up with my boyfriend, but I really want him back. Is he my future husband and does he still love me?'},
      { question: 'Do I need to worry about anything from his past? Can I trust him? Is he a good person?'},
      { question: 'I think that I fell in love with my colleague. Should I tell him about my feelings? Is it a right time?'},
      { question: 'Should I message him and tell that I miss him? Is that a good idea? Would it bring him to me faster?'},
      { question: 'Is it good idea to go for a date tomorrow with…?'},
      { question: 'Will I marry a millionaire?'},
      { question: 'Will I get pregnant this year?'},
      { question: 'What name should I choose for my first child? Could you advise me on how to select it?'},
      { question: 'I’m in love with a married man. He says that he is divorcing soon. Is it really so? Will he be with me or stays with his wife?'},
      { question: 'My boyfriend and I are in different locations now. Will we be together anyway?'},
      { question: 'Can you check if my boyfriend is being faithful?'},
      { question: 'I met a guy from the internet and he asked me out for a date. Should I agree? How can I trust him?'},
      { question: 'Does the guy I met today likes me as more than a friend?'},
      { question: 'Can I trust him to be faithful even before we are officially in a relationship? How do I know that?'},
      { question: 'Every time I get to a point where it feels we are getting closer, it seems he pulls back, why does he do that?'},
      { question: 'Can my boyfriend and I ever manage to understand each other?'},
      { question: 'Can I trust my boyfriend and let him spend separately the upcoming holidays?'},
      { question: 'I have issues with my marriage. I am not happy with our relationship. Would I find happiness in another relationship or should I stay in the marriage?'},
      { question: 'I am a divorcee. Will I marry again? When?'},
      { question: 'How many children will I have during my whole life?'},
      { question: 'I am single right now and afraid if I agree for the relationship it will prevent my career growth, what should I do?'},
      { question: 'What date is the best for my wedding this year?'},
      { question: 'My future husband and I are from different cities, which city should we choose for the wedding ceremony?'},
      { question: 'Does my boyfriend love me as much as I do or he is with me just because of comfort and a good financial situation?'}
    ],
    iconLeft: 'heart',
  },
  { title: 'Self',
    content: [
      { question: 'Am I on the right path according to astrology and destiny? What would be a good path for me right now?'},
      { question: 'Can you tell me more about myself? Sometimes I feel like I don’t know what my real personality is?'},
      { question: 'What does near future hold for me? Can I expect anything exciting in my life soon?'},
      { question: 'Do people like to be around me?'},
      { question: 'Does my chart indicate anything about realizing my life purpose?'},
      { question: 'How gemstones influence on our mind? How can I know which gemstone is suitable for me?'},
      { question: 'Does my future hold anything big, like fame or significant notable success?'},
      { question: 'When is the best time to start a fitness program and quit smoking to avoid extra stress?'},
      { question: 'I want to have a pet. Which animal will I be happy with?'},
      { question: 'If the destiny is written, so what do the stars say about mine?'},
      { question: 'What colors in clothes should I have more to save my inner energy, be more balanced, attract people?'},
      { question: 'Can I ever become an astrologer? If I finish courses or special talent needed? Do I have a good intuition?'},
      { question: 'Everything in my life is not going as planned. What is my ultimate destiny? What and who am I fated to become?'},
      { question: 'Why do I face the same problems during my life?'},
      { question: 'Do you recommend any mantras to clear my path?'},
      { question: 'Am I addicted to food too much? How can I deal wit it?'},
      { question: 'I feel very empty and hopeless at the moment. I have no career, no partner, no big plans. I hope it changes for the better soon, can you advise something?'},
      { question: 'What are strong and weak sides of my personality? Which qualities should I improve in myself?'},
      { question: 'Do you have any advice for meditations, mantras, or gems that can increase positive effect on me at the current moment?'},
      { question: 'Do the stars and planets have good advice for me how to make my will, confidence and self-love stronger?'},
      { question: 'Do I need to lose any weight or change anything in my appearance?'},
      { question: 'What’s best for me according to Vedic astrology, should I focus on career, continuing my education, or having a family?'},
      { question: 'I feel like I’m a perfect woman – pretty, smart, loving, ambitious. But I never attract men on my level and it’s painful. I don’t want to be alone.'},
      { question: 'Does someone have a black magic, evil eye or voodoo doll on me? It looks like I’ve had less luck lately. What is going on?'},
      { question: 'How long will this difficult period continue? Can you recommend a gemstone to help me with motivation?'},
      { question: 'What kind of sports activities suit me best?'},
      { question: 'According to my birth chart and all the information you get from it. Would I make a good leader?'},
      { question: 'Are there people who negatively influence on me?'},
      { question: 'Does destiny love me? Or did I miss my destiny? where am I supposed to be?'},
      { question: 'I have been singing and songwriting since childhood. Some music labels suggest me contracts, am I ready? Which can I devote?'},
      { question: 'How to deal with all the stress I have?'},
      { question: 'Everyone has a purpose in life. How do I know what is mine?'},
      { question: 'Does it look like that I need to find myself spiritually? I feel like I do not know what direction to take in my life. Which path is better for me?'},
      { question: 'I play in school performances. Can I become famous actress If I move to Hollywood? Or better to concentrate on other fields?'},
      { question: 'Do you think I have a greater purpose in life that what I see myself in? Was I destined to become a light, leader or savior?'},
      { question: 'Do coffee and sugar really reflect on me? Will I notice real improvements if refuse these products?'},
      { question: 'People treat me bad, hope that it will improve but it’s not. Because of this I can see no positive future. What can you advise me?'},
      { question: 'What is the thing I need to do for myself to start becoming truly happier?'},
      { question: 'Do I have good intuition? Can I really sense spirits? Sometimes I have dreams of things before it happens. Do I have potential in spirituality?'},
      { question: 'Everyone is married with children and it’s a dream of mine and I am scared that it will never happen. What if it doesn’t?'},
      { question: 'I always expect too much from people around me. Is something wrong with them or I really expect too much? Can you show me the way to stop unrealistic expectations?'},
      { question: 'How can I learn to accept and love all of myself especially those aspects of who I am that I judge and feel ashamed about?'},
      { question: 'Nothing has gone right for me for the last couple of years. When will things improve?'},
      { question: 'Do I have a curse or bad luck and how can I have good luck from this point?'},
      { question: 'The extreme responsibilities are causing me great anxiety. Will this end or is it just a part of my destiny that never will change?'},
      { question: 'Everything is changing at once for me. I don’t know I will be able to keep myself through it all. What does my birth chart say?'},
      { question: 'I’m having a difficult time understanding my purpose in life and my true calling. Do you have an idea of the direction I should go?'},
      { question: 'Do you have any inspirational news from my chart for the upcoming month?'},
      { question: 'What am I here to learn in this life? What is the mission of my life?'},
      { question: 'I am a musician. I play musical instruments and sing. Will I become a famous musician one day?'},
      { question: 'Am I going to have a long and happy life? Am I gonna have the life I want?'},
      { question: 'I believe my destiny is to help people, is it really so? Which areas should I choose, according to the natal chart?'},
      { question: 'I have a classmate meeting this weekend and really afraid to go because 10 years have passed and I didn’t do any outstanding things in my life.'},
      { question: 'Could you advise me a crystal or stone to wear that would help give me confidence or a positive attitude?'},
      { question: 'Is now an auspicious time for personal growth? If so, what areas might I focus on?'},
      { question: 'Do I have any future in the professional sport? How can I improve myself in this field?'},
      { question: 'I feel like my motivation and influence of the planets are strongly driving me in the right direction now. I am wondering what is my next major turn?'},
      { question: 'What is my lucky number?'},
      { question: 'I’m feeling very depressed, stressed out and unmotivated to work, what’s wrong with me? Please help me cope more effectively?'},
    ],
    iconLeft: 'person',
  },
  {
    title: 'Everyday Life',
    content: [
      { question: 'Can I expect any type of surprises this week either good or bad? If so, what kind?' },
      { question: 'Does it look favorable to have a cosmetic procedure tomorrow?'},
      { question: 'Can I expect to hear from my friends today? Do you know how they may be feeling about me?'},
      { question: 'Feeling nervous about my competition this weekend. Will I do ok? Is there anything I can do to ensure everything runs smoothly on the day?'},
      { question: 'Will I go for a vacation in the beginning of June? Because I have some obstacles and tomorrow I will get the final result. What does my birth chart show?'},
      { question: 'Can I have some insight as to what today holds for me?'},
      { question: 'I plan to have some remodeling at home this year When is the best time to start?'},
      { question: 'I have lost my wedding ring. When will I need to tell what happened? What is the best time and what will be the outcome?'},
      { question: 'If I delete my profiles from all social medias. Will it make my life better?'},
      { question: 'Is there a special alignment of things in a house to feel more happy and balanced inside?'},
      { question: 'What is the best day to go shopping this month ?'},
      { question: 'Does it look favorable and safe to have a long car drive tomorrow or better to postpone it?'},
      { question: 'I told him today he needs to make a decision if he wants me or not. What will he choose?'},
      { question: 'Why am I so sad this week? Can you give me some advice on how to feel better?'},
      { question: 'According to my natal chart, what type of books should I read now?'},
      { question: 'The buyer for my property backed out saying it was too expensive. what is your advice?'},
      { question: 'When is the best time for me to have a new haircut?'},
      { question: 'Can I ask for financial help from my friend today?'},
      { question: 'Will I meet someone special if I go to the party on Friday?'},
      { question: 'What kind of perfume or scented oils should I use to attract people?'},
      { question: 'It is trendy to become vegetarian. Should I become? Will it really improve me?'},
      { question: 'I like a guy for a long time and finally decided to ask him for a date. What is the best time tomorrow to call him? Or better to text?'},
      { question: 'Do I have extra luck today? I need to accomplish a very important deal.'},
      { question: 'I had a bad day yesterday. It was hard to control my feelings and emotions. How does this fall under my sign and tomorrow’s outlook?'},
      { question: 'I plan to rent an apartment but hesitate between several variants. Where will I feel more comfortable and happy? And what is the best time to move?'},
      { question: 'Should I buy a dog or adopt a homeless puppy?'},
      { question: 'I worry that I won’t be able to make a clear decision if offered a promotion. Will I have to make the decision with my head or heart?'},
      { question: 'Do you see how I can gain more motivation this week? I have a lack of energy or will to do anything. Why is that?'},
      { question: 'Will the guy I like come to my birthday party this Friday?'},
      { question: 'Did I make an impression on a colleague today that I met the last month?'},
      { question: 'Can you tell me how the party I am hosting today will go? Will the party go off as planned? Will the guests of honor be pleased with the event?'},
      { question: 'Did I make the right choice ordering movie tickets for tomorrow? Will we really have a good time?'},
      { question: 'Can I give resignation letter today? I want to rest at home for 2 months then start work. Is this good idea?'},
      { question: 'What did he think about my beautiful dress today? Did he feel jealous towards my Ex-boyfriend?'},
      { question: 'Give me some positive news. I really need some hope and encouragement these days.'}
    ],
    iconLeft: 'calendar',
  },
  {
    title: 'Education',
    content: [
      {question: 'Am I on the right educational path? What are good fields for me to study?'},
      { question: 'Will I get admission into my choice of college this year?'},
      { question: 'After achieving bachelor degree should I continue education or start working?'},
      { question: 'It’s difficult for me to concentrate on studying process. What can I do to improve it?'},
      { question: 'My parents want me to become a lawyer. But I don’t feel like I can be a successful one. What do you see in my birth chart?'},
      { question: 'Currently, I am working as a professor. I want some development in my career and qualifications. Is it still possible?'},
      { question: 'Does the teacher I work with this year have feelings for me? Will it affect my studies?'},
      { question: 'I have a team project in university and really afraid that we will fail it because of some members. Can I really trust and be confident in them?'},
      { question: 'Can I bring my math grade up and pass before the semester ends? What is my education horoscope for this year?'},
      { question: 'I would like to know what is best outlook on life for me. Should I focus on continuing my education or having a family?'},
      { question: 'Can I become a famous personality in college? What fields should I focus on?'},
      { question: 'Does the chart reflect anything about returning to formal education such as acquiring a masters degree?'},
      { question: 'I failed exams to a medical school and it was my dream. Why did it happen?'},
      { question: 'Will I be able to get my education abroad one day and settle there? When?'},
      { question: 'Am I gonna make the high school soccer team?'},
      { question: ' How will the situation turn out? Could you check when is the right time?'},
      { question: 'I want to join university football team, if I train every day will I get the invitation?'},
      { question: 'I got accepted into two colleges. How can I choose the best one for me? I am out of any idea how to make this decision.'},
      { question: 'Can I get an internship this semester?'},
      { question: 'I found a good job, but still a student and plan to leave the university. Should I really do it? What is my destiny in regard to my education?'},
      { question: 'I have a communication problem with my professor, how can I manage it? If I need to talk frankly with him what is the best time when planets support me?'},
      { question: 'Can you tell me if there will be someone in my classes that likes me this year? Do I have any classes with the guy who will ask me out?'},
      { question: 'What does my math teacher think about me? I’m really talented in class, but I feel a little forgotten by him.'},
      { question: 'Does the program director at my college want to hire me as an intern based on my yesterday interview?'},
      { question: 'I have a difficult relationship with my classmates. Why is this happening?'},
      { question: 'If I get married this year will I be able to continue education?'},
      { question: 'When will I find a job which satisfies my educational background or should I go to studies again?'},
      { question: 'My boyfriend is leaving for another country to study, could we support our relationship, despite the distance or should I attend studies abroad as well?'},
      { question: 'I study a lot but anyway get bad grades. Why is it happening? Will I complete my education?'},
      { question: 'Have the teachers I have been working with saying good things about me to my professor?'},
      { question: 'I think that my professor gives me low grades just because he doesn’t like me, is that true? If yes then what solution you see in accordance with my natal chart.'},
      { question: 'I am not doing good in studies at the moment. Do my classmates respect me?'},
      { question: 'I’m having important exams next week. Will I get a needed score? Will I get the scholarship this year?'},
      { question: 'I am a teacher now. What does my chart say about education? Should I get my masters in art education or pursue art therapy in the future?'},
    ],
    iconLeft: 'book',
  },
  {
    title: 'Work',
    content: [
      { question: 'When will I get a job?'},
      { question: 'Will I get a promotion at work this year?'},
      { question: 'Is it a good idea to accept a new job offer now?'},
      { question: 'I have just accepted a new job offer. How should I behave with my new co-workers? What will be the atmosphere in my new workplace?'},
      { question: 'I have an important job interview tomorrow, is it a good date for the interview to be successful? What can I do to make it successful?'},
      { question: 'I was promoted to a manager position, can you give me career guidance how to mentor it all correctly'},
      { question: 'Can I be a good boss? Will people love me? What does my birth chart say?'},
      { question: 'Why can’t I find a job? How to deal with it?'},
      { question: 'I am having a problem at work with my boss. Do you think things will improve or will I have to quit?'},
      { question: 'I didn’t receive even one invitation to the job interview during last 2 months. What is wrong?'},
      { question: 'Should I accept a job offer in another city?'},
      { question: 'I am a housewife and I feel really bored. But if I get a job, could I handle it? Will I be successful?'},
      { question: 'Dismissals started to happen in my office, will it touch me?'},
      { question: 'I had an important job interview today but didn’t get any feedback yet, how was it? Will they hire me?'},
      { question: 'In what ways should I develop myself to come over interviews more efficient?'},
      { question: 'Which days and time are the best for me to appoint a job interview?'},
      { question: 'Sometimes I feel very confident during the interview and sometimes really lost and confused, why is this happening?'},
      { question: 'I like a guy from my office, should I ask him out for a date or will it spoil our professional relationship?'},
      { question: 'I want to get a job, but my husband doesn’t want me to work, what should I do?'},
      { question: 'I feel I meant to do something big in life but I am having trouble figuring out what it is. Is it related to my career?'},
      { question: 'I am afraid to agree with job promotion because of my colleagues would be jealous and might not support me. What should I do?'},
      { question: 'I don’t like my job at all, how can I get a job of my dream?'},
      { question: 'What does my birth chart show about my work atmosphere and career progress this year?'},
      { question: 'Will I get a salary increase this year?'},
      { question: 'I’ve had more than 10 job interviews but I didn’t receive any offers. What is wrong?'},
      { question: 'People say that clothes matter during a job interview. What should I wear for the interview tomorrow? Colours? Some bringing luck gemstones?'},
      { question: 'I have received several job offers. Which one should I choose?'},
      { question: 'I think my boss offers me a promotion with a salary increase because he likes me. If I agree will he want to get something instead?'},
      { question: 'One of my colleagues always misrepresents me. Why does she do it? How to deal with it?'}
    ],
    iconLeft: 'git-network',
  },
  {
    title: 'Money',
    content: [
      { question: 'Tell me what important thing should I know about money in my future.' },
      { question: 'Will I become rich one day?'},
      { question: 'I feel like my husband is keeping secret our financial situation, is he? Is it better than he tells me or worse?'},
      { question: 'Will I ever be financially independent of my family?'},
      { question: 'I am going to take out a loan, when is the best date to apply for it?'},
      { question: 'Will I have enough money to buy my own house one day?'},
      { question: 'I need some money, is it better to borrow from friends or take a loan from a bank?'},
      { question: 'Will I be able to get a loan from a bank?'},
      { question: 'A lot of people tell me that I will not ever be able to save money. Is that true?'},
      { question: 'My friend wants me to lend him some money? Will it affect our friendship?'},
      { question: 'Why am I facing debts and losses?'},
      { question: 'Will I get a sudden fortune or lottery luck?'},
      { question: 'My husband borrowed a lot of money for business. We are struggling to pay back. Are there in the future any more issues like this?'}
    ],
    iconLeft: 'logo-usd',
},
  {
    title: 'Bussiness',
    content: [
      { question: 'According to my birth chart, can I be a good businessman?' },
      { question: 'When will be a good time to invest my money?'},
      { question: 'If I open a store with handmade organic cosmetics will it be successful?'},
      { question: 'I am tired being just an employee. Will I get a proposal for partnership? Or it is better to start my own business?'},
      { question: 'I was asked to become a business partner of my friend. Should I agree?'},
      { question: 'I am working on a big project at present. Will it be successful? Will I make money or lose money?'},
      { question: 'I am a makeup artist. If I start online video blog will I become successful and famous?'},
      { question: 'I want to retire. Should I sell my business or find a partner who will take care of it?'},
      { question: 'If I merge my company with my major competitor will it pay off in the long-term perspective?'}
    ],
    iconLeft: 'logo-bitcoin',
  },
];

export const test = 'test';
